In [1]:
import numpy as np

# Creating a 1D array
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)

1D Array:
[10 20 30 40 50]


In [2]:
# Creating a 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Creating a 3D array
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print("3D Array:")
print(arr3)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
arr = np.array([10,20,30,40,50,60])

print("Original Array:", arr)

# Slicing elements
print("Elements from index 1 to 4:", arr[1:5])
print("Elements from index 2 onwards:", arr[2:])
print("First 3 elements:", arr[:3])

Original Array: [10 20 30 40 50 60]
Elements from index 1 to 4: [20 30 40 50]
Elements from index 2 onwards: [30 40 50 60]
First 3 elements: [10 20 30]


In [5]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

# Access specific elements
print("Element:", arr[0,2])

# Slicing rows and columns
print("First row:", arr[0,:])
print("Second column:", arr[:,1])

Element: 3
First row: [1 2 3 4]
Second column: [2 6]


In [6]:
arr = np.array([1,2,3,4,5])

copy_arr = arr.copy()

arr[0] = 100

print("Original Array:", arr)
print("Copied Array:", copy_arr)

Original Array: [100   2   3   4   5]
Copied Array: [1 2 3 4 5]


In [9]:
arr = np.array([1,2,3,4,5])

view_arr = arr.view()

arr[0] = 100

print("Original Array:", arr)
print("View Array:", view_arr)

Original Array: [100   2   3   4   5]
View Array: [100   2   3   4   5]


In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

joined = np.concatenate((arr1, arr2))

print("Joined Array:")
print(joined)

Joined Array:
[1 2 3 4 5 6]


In [10]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

joined = np.concatenate((arr1, arr2), axis=0)

print("Joined 2D Array:")
print(joined)

Joined 2D Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
